name: Run MATLAB Script

on:
  push:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: R2022aU3

      - name: Run Script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("src"); hello
